Music-Genre-Classification-Django-master/MusicClassification/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('predictor.urls')),
    path('admin/', admin.site.urls)
]


if settings.DEBUG:
    #test mode
    from django.conf.urls.static import static
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Music-Genre-Classification-Django-master/predictor/urls.py
from django.urls import path
from . import views

app_name = 'predictor'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('result/',views.model_form_upload,name = 'result'),
]

Music-Genre-Classification-Django-master/predictor/models.py
from django.db import models

# Create your models here.
class Document(models.Model):
    file = models.FileField(upload_to='file/')

Music-Genre-Classification-Django-master/predictor/forms.py
from django import forms
from .models import Document

class DocumentForm(forms.Form):
    def is_valid(*args, **kwargs):
        return True

    file = forms.FileField(help_text='Valid .mp3 file')

Music-Genre-Classification-Django-master/predictor/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView
from .apps import PredictorConfig
from .forms import DocumentForm
from .models import Document
from .Metadata import getmetadata
import warnings
from .predict import predict_gen
from django.contrib import messages
warnings.simplefilter('ignore')

class IndexView(ListView):
    template_name= 'music/index.html'
    def get_queryset(self):
        return True

def model_form_upload(request):

    documents = Document.objects.all()
    if request.method == 'POST':
        if len(request.FILES) == 0:
            messages.error(request,'Upload a file')
            return redirect("predictor:index")

        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            uploadfile = request.FILES['document']
            print(uploadfile.name)
            print(uploadfile.size)
            if not uploadfile.name.endswith('.wav'):
                messages.error(request,'Only .wav file type is allowed')
                return redirect("predictor:index")
            meta = getmetadata(uploadfile)
            
            genre = predict_gen(meta)
            print(genre)

            context = {'genre':genre}
            return render(request,'music/result.html',context)

    else:
        form = DocumentForm()

    return render(request,'music/result.html',{'documents':documents,'form':form})

Music-Genre-Classification-Django-master/predictor/templates/music/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Music Genre Classification</title>
	<link rel="icon" href="{% static 'music/images/headphone.png' %}">
</head>

<body id="page-top">

	  <!-- Preloader -->
<div class="spinner-wrapper">
      <div class="spinner">
          <div class="bounce1"></div>
          <div class="bounce2"></div>
          <div class="bounce3"></div>
      </div>
 </div>
  <!-- end of preloader -->

  {% include 'music/snippets/nav.html' %}

   <div class="content">

    {% block content %}

    <!-- content for different pages here -->

    {% endblock content %}
  </div>


  {% include 'music/snippets/js.html' %}

</body>
<script>
    $(document).ready(function(){
        $('.up-input').change(function () {
            $('.up-p').text(this.files.length + " file(s) selected");
        });
    });

    
</script>
<!-- Bootstrap core JavaScript -->

</html>

Music-Genre-Classification-Django-master/predictor/templates/music/check_genre.html
{% extends 'music/base.html' %}
{% load static %}
{% block content %}

<div id="basic-2" class="tabs">
    <div class="container">
      <a id="errormess"></a>

        <div class="row">
            <div class="col-lg-12" style="margin-bottom: 6rem;">
              <a id="errormess">
              {% include 'music/messages.html' %}

                <h2>CHECK GENRE</h2>
                <div class="p-heading p-large">Here you can drag and drop your music file or click on the area and upload your music file to check genre of the music.</div>
            </div> <!-- end of col -->
        </div>
        <div class="row">
            <form action="{% url 'predictor:result' %}" method="POST" enctype="multipart/form-data" class="up-form">
               {% csrf_token %}
               <input type="file" name='document' multiple="" class="up-input">
               {{form.as_table}}
              <p class="up-p">Drag your music file here or click in this area.</p>
              <button type="submit" class="btn btn-sm btn-success" style="margin-left: 9rem; width: 30vh;">Check</button>

            </form>
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</div> <!-- end of basic-2 -->
<!-- end of File Upload -->

{% endblock %}

{% block js%}
<script>
    $(document).ready(function(){
        $('.up-input').change(function () {
            $('.up-p').text(this.files.length + " file(s) selected");
        });
    });
</script>
{%endblock%}

Music-Genre-Classification-Django-master/predictor/templates/music/index.html
{% extends 'music/base.html' %}
{% load static %}

	<!-- Favicon  -->
 <link rel="icon" href="{% static 'music/images/headphone.png' %}">
</head>
<body data-spy="scroll" data-target=".fixed-top">

    <!-- Preloader -->
	<div class="spinner-wrapper">
        <div class="spinner">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
    </div>
    <!-- end of preloader -->



{% block content %}
    <!-- Header -->
    <header id="header" class="header">
        <div class="header-content">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7">
                        <div class="text-container">
                            <h4>A music genre classification for 
                                <span id="js-rotating">
                                    , METAL, DISCO, CLASSICAL, HIPHOP, JAZZ, COUNTRY, POP, BLUES, REGGAE, ROCK
                                </span>
                            </h4>
                            <a class="btn-solid-lg page-scroll mt-4" href="#basic-2"><i class="fas fa-headphones"></i> GET STARTED</a>
                        </div>				

					<div class="col-lg-5">
                        <div class="image-container">
                            <img class="img-fluid" src="{% static 'music/images/guitar.png' %}" alt="alternative">
                        </div> <!-- end of image-container -->
                    </div> <!-- end of col -->
                </div> <!-- end of row -->
            </div> <!-- end of container -->
        </div> <!-- end of header-content -->
    </header> <!-- end of header -->
    <!-- end of header -->



    <!-- File Upload -->
    {% include 'music/check_genre.html' %}


    <!-- Statistics -->
    <div class="counter" id="statistics">
        <div class="row">
            <div class="col-lg-12">
                <h2>STATISTICS</h2>
            </div>
        </div>
        <div class="container" style="margin-top: 3rem;">
            <div class="row">
                <div class="col-lg-12">

                    <!-- Counter -->
                    <div id="counter">
                        <div class="cell">
                            <div class="counter-value number-count" data-count="1000"&nbsp>1</div>
                           
                            <p class="counter-info">Total Music</p>
                        </div>

                        <div class="cell">
                            <div class="counter-value number-count" data-count="750">1</div>
                            <p class="counter-info">Training Set</p>
                        </div>
                        <div class="cell">
                            <div class="counter-value number-count" data-count="250">1</div>
                            <p class="counter-info">Testing Set</p>
                        </div>
                        <div class="cell">
                            <div class="counter-value number-count" data-count="73.20">1</div>
                            <p class="counter-info">Accuracy (%)</p>
                        </div>
                    </div>
                    <!-- end of counter -->

                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </div> <!-- end of counter -->
    <!-- end of statistics -->

                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </div> <!-- end of form -->
    <!-- end of contact -->

{% endblock %}

</body>

</html>

Music-Genre-Classification-Django-master/predictor/templates/music/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <center><font size="6" color="red">{{ message }}</font>
  </div></center>
{% endfor %}

Music-Genre-Classification-Django-master/predictor/templates/music/result.html
{{file.name}}
{%load static%}
<html lang="en">
<head>

	<title>Music Genre Classification</title>

<!-- Styles -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700,700i" rel="stylesheet">
    <link href="{% static 'music/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'music/css/fontawesome-all.css' %}" rel="stylesheet">
    <link href="{% static 'music/css/swiper.css' %}" rel="stylesheet">
  	<link href="{% static 'music/css/magnific-popup.css' %}" rel="stylesheet">
  	<link href="{% static 'music/css/styles.css' %}" rel="stylesheet">
  	<link href="{% static 'music/css/mystyle.css' %}" rel="stylesheet">

    <!-- Favicon  -->
    <link rel="icon" href="{% static 'music/images/headphone.png' %}">

</head>

<body data-spy="scroll" data-target=".fixed-top">
<!-- Preloader -->
<div class="spinner-wrapper">
    <div class="spinner">
        <div class="bounce1"></div>
        <div class="bounce2"></div>
        <div class="bounce3"></div>
    </div>
</div>
<!-- end of preloader -->


<div id="features" class="tabs">
    <div class="container">
        <div class="card right-pane" style="margin-top: -5rem;">
            <div class="card-body">
                <div class="card-icon">
                    <a title="Close (Esc)" href="{% url 'predictor:index' %}" style="color: white">
                      <i class="fas fa-backward"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <h2>Your Music's Genre is</h2>
                <div class="col-md-12">
                    <div class="row mt-5">
                        <div class="col-md-4">
                            <img class="img-fluid" src="{% static 'music/images/celebration-1.png' %}" alt="alternative">
                        </div>
                        <div class="col-md-4">
                            <div class="card right-pane" style="margin-top: -5rem;">
                                <div class="card-body">
                                    <div class="card-icon" style="height: 38vh; width: 38vh; margin-top: 6rem; margin-left: 3rem; background-color: blueviolet">
                                        <h3 style="margin-top: 7rem;">
                                        <i>
                                        	{{ genre }}
                                        </i>
                                        </h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <img class="img-fluid" src="{% static 'music/images/celebration-2.png' %}" style="height: 300px;" alt="alternative">
                        </div>
                    </div>
                </div>
            </div> <!-- end of col -->
        </div> <!-- end of row -->



</div>
</div>


{%include 'music/snippets/js.html'%}
</body>
</html>

Music-Genre-Classification-Django-master/predictor/templates/music/snippets/footer.html
<!-- Footer -->
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="footer-col last">
                    <h4>Social Media</h4>
                    <span class="fa-stack">
                        <a href="#your-link">
                            <i class="fas fa-circle fa-stack-2x"></i>
                            <i class="fab fa-facebook-f fa-stack-1x"></i>
                        </a>
                    </span>
                    <span class="fa-stack">
                        <a href="#your-link">
                            <i class="fas fa-circle fa-stack-2x"></i>
                            <i class="fab fa-twitter fa-stack-1x"></i>
                        </a>
                    </span>
                    <span class="fa-stack">
                        <a href="#your-link">
                            <i class="fas fa-circle fa-stack-2x"></i>
                            <i class="fab fa-google-plus-g fa-stack-1x"></i>
                        </a>
                    </span>
                    <span class="fa-stack">
                        <a href="#your-link">
                            <i class="fas fa-circle fa-stack-2x"></i>
                            <i class="fab fa-instagram fa-stack-1x"></i>
                        </a>
                    </span>
                    <span class="fa-stack">
                        <a href="#your-link">
                            <i class="fas fa-circle fa-stack-2x"></i>
                            <i class="fab fa-linkedin-in fa-stack-1x"></i>
                        </a>
                    </span>
                </div>
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</div> <!-- end of footer -->
<!-- end of footer -->


<!-- Copyright -->
<div class="copyright">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <p class="p-small">Copyright © Electronics And Computer Department, <a href="https://www.wrc.edu.np">WRC</a></p>
            </div> <!-- end of col -->
        </div> <!-- enf of row -->
    </div> <!-- end of container -->
</div> <!-- end of copyright -->
<!-- end of copyright -->

Music-Genre-Classification-Django-master/predictor/templates/music/snippets/js.html
{%load static %}
<!-- Scripts -->
<script src="{% static 'music/js/jquery.min.js' %}"></script> <!-- jQuery for Bootstrap's JavaScript plugins -->
<script src="{% static 'music/js/jquery.simple-text-rotator' %}"></script>
<script src="{% static 'music/js/jquery.simple-text-rotator.min' %}"></script>
<script src="{% static 'music/js/popper.min.js' %}"></script> <!-- Popper tooltip library for Bootstrap -->
<script src="{% static 'music/js/bootstrap.min.js' %}"></script> <!-- Bootstrap framework -->
<script src="{% static 'music/js/jquery.easing.min.js' %}"></script> <!-- jQuery Easing for smooth scrolling between anchors -->
<script src="{% static 'music/js/swiper.min.js' %}"></script> <!-- Swiper for image and text sliders -->
<script src="{% static 'music/js/jquery.magnific-popup.js' %}"></script> <!-- Magnific Popup for lightboxes -->
<script src="{% static 'music/js/morphext.min.js' %}"></script> <!-- Morphtext rotating text in the header -->
<script src="{% static 'music/js/validator.min.js' %}"></script> <!-- Validator.js - Bootstrap plugin that validates forms -->
<script src="{% static 'music/js/scripts.js' %}"></script> <!-- Custom scripts -->
<script src="https://kit.fontawesome.com/99cff280a5.js' %}"></script>
<script src="{% static 'music/js/chart.bundle.js' %}"></script>
<script src="{% static 'music/js/utils.js' %}"></script>

Music-Genre-Classification-Django-master/predictor/templates/music/snippets/nav.html
{% load static %}
<!-- Styles -->
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,600,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700,700i" rel="stylesheet">
<link href="{% static 'music/css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'music/css/fontawesome-all.css' %}" rel="stylesheet">
<link href="{% static 'music/css/swiper.css' %}" rel="stylesheet">
<link href="{% static 'music/css/magnific-popup.css' %}" rel="stylesheet">
<link href="{% static 'music/css/styles.css' %}" rel="stylesheet">
<link href="{% static 'music/css/mystyle.css' %}" rel="stylesheet">
<link href="{% static 'music/css/simpletextrotator.css' %}" rel="stylesheet">

<!-- Navbar -->
<nav class="navbar navbar-expand-md navbar-dark navbar-custom fixed-top" style="height: 15%">
    <!-- Text Logo - Use this if you don't have a graphic logo -->
    <!-- <a class="navbar-brand logo-text page-scroll" href="index.html">Leno</a> -->

    <a class="navbar-brand" style="text-decoration: none;" href="{% url 'predictor:index' %}"><font color="8ac6d1">MUSIC GENRE CLASSIFIER</font></a>

    <!-- Mobile Menu Toggle Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- end of mobile menu toggle button -->

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link page-scroll" href="#header">HOME <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link page-scroll" href="#basic-2">CHECK GENRE</a>
            </li>
            <li class="nav-item">
                <a class="nav-link page-scroll" href="#statistics">STATISTICS</a>
            </li>
        </ul>
    </div>

</nav> <!-- end of navbar -->
<!-- end of navbar -->